//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.UserSoap")]
    public interface UserSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (all_x0020_user) of message all_x0020_user does not match the default value (ReturnUser)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/all user", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApplication1.ServiceReference2.alluser1 ReturnUser(ConsoleApplication1.ServiceReference2.alluser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/all user", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference2.alluser1> ReturnUserAsync(ConsoleApplication1.ServiceReference2.alluser request);
        
        // CODEGEN: Generating message contract since the wrapper name (return_x0020_by_x0020_username_x0020_and_x0020_password) of message return_x0020_by_x0020_username_x0020_and_x0020_password does not match the default value (ReturnUser1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/return by username and password", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApplication1.ServiceReference2.returnbyusernameandpassword1 ReturnUser1(ConsoleApplication1.ServiceReference2.returnbyusernameandpassword request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/return by username and password", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference2.returnbyusernameandpassword1> ReturnUser1Async(ConsoleApplication1.ServiceReference2.returnbyusernameandpassword request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="all user", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class alluser {
        
        public alluser() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="all userResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class alluser1 {
        
        public alluser1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="return by username and password", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class returnbyusernameandpassword {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        public returnbyusernameandpassword() {
        }
        
        public returnbyusernameandpassword(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="return by username and passwordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class returnbyusernameandpassword1 {
        
        public returnbyusernameandpassword1() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserSoapChannel : ConsoleApplication1.ServiceReference2.UserSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserSoapClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference2.UserSoap>, ConsoleApplication1.ServiceReference2.UserSoap {
        
        public UserSoapClient() {
        }
        
        public UserSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference2.alluser1 ConsoleApplication1.ServiceReference2.UserSoap.ReturnUser(ConsoleApplication1.ServiceReference2.alluser request) {
            return base.Channel.ReturnUser(request);
        }
        
        public void ReturnUser() {
            ConsoleApplication1.ServiceReference2.alluser inValue = new ConsoleApplication1.ServiceReference2.alluser();
            ConsoleApplication1.ServiceReference2.alluser1 retVal = ((ConsoleApplication1.ServiceReference2.UserSoap)(this)).ReturnUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference2.alluser1> ConsoleApplication1.ServiceReference2.UserSoap.ReturnUserAsync(ConsoleApplication1.ServiceReference2.alluser request) {
            return base.Channel.ReturnUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference2.alluser1> ReturnUserAsync() {
            ConsoleApplication1.ServiceReference2.alluser inValue = new ConsoleApplication1.ServiceReference2.alluser();
            return ((ConsoleApplication1.ServiceReference2.UserSoap)(this)).ReturnUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference2.returnbyusernameandpassword1 ConsoleApplication1.ServiceReference2.UserSoap.ReturnUser1(ConsoleApplication1.ServiceReference2.returnbyusernameandpassword request) {
            return base.Channel.ReturnUser1(request);
        }
        
        public void ReturnUser1(string username, string password) {
            ConsoleApplication1.ServiceReference2.returnbyusernameandpassword inValue = new ConsoleApplication1.ServiceReference2.returnbyusernameandpassword();
            inValue.username = username;
            inValue.password = password;
            ConsoleApplication1.ServiceReference2.returnbyusernameandpassword1 retVal = ((ConsoleApplication1.ServiceReference2.UserSoap)(this)).ReturnUser1(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference2.returnbyusernameandpassword1> ConsoleApplication1.ServiceReference2.UserSoap.ReturnUser1Async(ConsoleApplication1.ServiceReference2.returnbyusernameandpassword request) {
            return base.Channel.ReturnUser1Async(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference2.returnbyusernameandpassword1> ReturnUser1Async(string username, string password) {
            ConsoleApplication1.ServiceReference2.returnbyusernameandpassword inValue = new ConsoleApplication1.ServiceReference2.returnbyusernameandpassword();
            inValue.username = username;
            inValue.password = password;
            return ((ConsoleApplication1.ServiceReference2.UserSoap)(this)).ReturnUser1Async(inValue);
        }
    }
}
