//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceClient.MessageServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime messageDateTimeField;
        
        private int messageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messagSenderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageRecierIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime messageDateTime {
            get {
                return this.messageDateTimeField;
            }
            set {
                if ((this.messageDateTimeField.Equals(value) != true)) {
                    this.messageDateTimeField = value;
                    this.RaisePropertyChanged("messageDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int messageID {
            get {
                return this.messageIDField;
            }
            set {
                if ((this.messageIDField.Equals(value) != true)) {
                    this.messageIDField = value;
                    this.RaisePropertyChanged("messageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string messages {
            get {
                return this.messagesField;
            }
            set {
                if ((object.ReferenceEquals(this.messagesField, value) != true)) {
                    this.messagesField = value;
                    this.RaisePropertyChanged("messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string messagSenderID {
            get {
                return this.messagSenderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.messagSenderIDField, value) != true)) {
                    this.messagSenderIDField = value;
                    this.RaisePropertyChanged("messagSenderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string messageRecierID {
            get {
                return this.messageRecierIDField;
            }
            set {
                if ((object.ReferenceEquals(this.messageRecierIDField, value) != true)) {
                    this.messageRecierIDField = value;
                    this.RaisePropertyChanged("messageRecierID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessageServiceReference.MessageWebServiceSoap")]
    public interface MessageWebServiceSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (return_x0020_all_x0020_message_x0020_from_x0020_single_x0020_user) of message return_x0020_all_x0020_message_x0020_from_x0020_single_x0020_user does not match the default value (GetMessage)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/return all message from single user", ReplyAction="*")]
        WebServiceClient.MessageServiceReference.returnallmessagefromsingleuser1 GetMessage(WebServiceClient.MessageServiceReference.returnallmessagefromsingleuser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/return all message from single user", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceClient.MessageServiceReference.returnallmessagefromsingleuser1> GetMessageAsync(WebServiceClient.MessageServiceReference.returnallmessagefromsingleuser request);
        
        // CODEGEN: Generating message contract since the wrapper name (send_x0020_message_x0020_fro_x0020_single_x0020_user) of message send_x0020_message_x0020_fro_x0020_single_x0020_user does not match the default value (sendMessagePerUser)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/send message fro single user", ReplyAction="*")]
        WebServiceClient.MessageServiceReference.sendmessagefrosingleuser1 sendMessagePerUser(WebServiceClient.MessageServiceReference.sendmessagefrosingleuser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/send message fro single user", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceClient.MessageServiceReference.sendmessagefrosingleuser1> sendMessagePerUserAsync(WebServiceClient.MessageServiceReference.sendmessagefrosingleuser request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="return all message from single user", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class returnallmessagefromsingleuser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sernderID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string reciverID;
        
        public returnallmessagefromsingleuser() {
        }
        
        public returnallmessagefromsingleuser(string sernderID, string reciverID) {
            this.sernderID = sernderID;
            this.reciverID = reciverID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="return all message from single userResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class returnallmessagefromsingleuser1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="return_x0020_all_x0020_message_x0020_from_x0020_single_x0020_userResult", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceClient.MessageServiceReference.Message[] returnallmessagefromsingleuserResult;
        
        public returnallmessagefromsingleuser1() {
        }
        
        public returnallmessagefromsingleuser1(WebServiceClient.MessageServiceReference.Message[] returnallmessagefromsingleuserResult) {
            this.returnallmessagefromsingleuserResult = returnallmessagefromsingleuserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="send message fro single user", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class sendmessagefrosingleuser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sernderID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string reciverID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string smessage;
        
        public sendmessagefrosingleuser() {
        }
        
        public sendmessagefrosingleuser(string sernderID, string reciverID, string smessage) {
            this.sernderID = sernderID;
            this.reciverID = reciverID;
            this.smessage = smessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="send message fro single userResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class sendmessagefrosingleuser1 {
        
        public sendmessagefrosingleuser1() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessageWebServiceSoapChannel : WebServiceClient.MessageServiceReference.MessageWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageWebServiceSoapClient : System.ServiceModel.ClientBase<WebServiceClient.MessageServiceReference.MessageWebServiceSoap>, WebServiceClient.MessageServiceReference.MessageWebServiceSoap {
        
        public MessageWebServiceSoapClient() {
        }
        
        public MessageWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceClient.MessageServiceReference.returnallmessagefromsingleuser1 WebServiceClient.MessageServiceReference.MessageWebServiceSoap.GetMessage(WebServiceClient.MessageServiceReference.returnallmessagefromsingleuser request) {
            return base.Channel.GetMessage(request);
        }
        
        public WebServiceClient.MessageServiceReference.Message[] GetMessage(string sernderID, string reciverID) {
            WebServiceClient.MessageServiceReference.returnallmessagefromsingleuser inValue = new WebServiceClient.MessageServiceReference.returnallmessagefromsingleuser();
            inValue.sernderID = sernderID;
            inValue.reciverID = reciverID;
            WebServiceClient.MessageServiceReference.returnallmessagefromsingleuser1 retVal = ((WebServiceClient.MessageServiceReference.MessageWebServiceSoap)(this)).GetMessage(inValue);
            return retVal.returnallmessagefromsingleuserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceClient.MessageServiceReference.returnallmessagefromsingleuser1> WebServiceClient.MessageServiceReference.MessageWebServiceSoap.GetMessageAsync(WebServiceClient.MessageServiceReference.returnallmessagefromsingleuser request) {
            return base.Channel.GetMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceClient.MessageServiceReference.returnallmessagefromsingleuser1> GetMessageAsync(string sernderID, string reciverID) {
            WebServiceClient.MessageServiceReference.returnallmessagefromsingleuser inValue = new WebServiceClient.MessageServiceReference.returnallmessagefromsingleuser();
            inValue.sernderID = sernderID;
            inValue.reciverID = reciverID;
            return ((WebServiceClient.MessageServiceReference.MessageWebServiceSoap)(this)).GetMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceClient.MessageServiceReference.sendmessagefrosingleuser1 WebServiceClient.MessageServiceReference.MessageWebServiceSoap.sendMessagePerUser(WebServiceClient.MessageServiceReference.sendmessagefrosingleuser request) {
            return base.Channel.sendMessagePerUser(request);
        }
        
        public void sendMessagePerUser(string sernderID, string reciverID, string smessage) {
            WebServiceClient.MessageServiceReference.sendmessagefrosingleuser inValue = new WebServiceClient.MessageServiceReference.sendmessagefrosingleuser();
            inValue.sernderID = sernderID;
            inValue.reciverID = reciverID;
            inValue.smessage = smessage;
            WebServiceClient.MessageServiceReference.sendmessagefrosingleuser1 retVal = ((WebServiceClient.MessageServiceReference.MessageWebServiceSoap)(this)).sendMessagePerUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceClient.MessageServiceReference.sendmessagefrosingleuser1> WebServiceClient.MessageServiceReference.MessageWebServiceSoap.sendMessagePerUserAsync(WebServiceClient.MessageServiceReference.sendmessagefrosingleuser request) {
            return base.Channel.sendMessagePerUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceClient.MessageServiceReference.sendmessagefrosingleuser1> sendMessagePerUserAsync(string sernderID, string reciverID, string smessage) {
            WebServiceClient.MessageServiceReference.sendmessagefrosingleuser inValue = new WebServiceClient.MessageServiceReference.sendmessagefrosingleuser();
            inValue.sernderID = sernderID;
            inValue.reciverID = reciverID;
            inValue.smessage = smessage;
            return ((WebServiceClient.MessageServiceReference.MessageWebServiceSoap)(this)).sendMessagePerUserAsync(inValue);
        }
    }
}
